### ISSUE TITLE
Got error when running

### ISSUE THREAD

**Issue by linux-root** [davesmith00000/snake-in-5-minutes-port#2]
Error when running `mill snakeIn5Minutes.runGame`:
<br/>
```
❯ mill snakeIn5Minutes.runGame
Mill version 0.12.4 is different than configured for this directory!
Configured version is 0.9.9 (/Users/kurro/IdeaProjects/snake-in-5-minutes-port/.mill-version)
[build.sc-64/68] compile
[build.sc-64] [info] compiling 1 Scala source to /Users/kurro/IdeaProjects/snake-in-5-minutes-port/out/mill-build/compile.dest/classes ...
[build.sc-64] [error] /Users/kurro/IdeaProjects/snake-in-5-minutes-port/build.sc:9:51: illegal inheritance; superclass BaseClass
[build.sc-64] [error]  is not a subclass of the supertrait Module
[build.sc-64] [error]  of the mixin trait MillIndigo
[build.sc-64] [error] object snakeIn5Minutes extends ScalaJSModule with MillIndigo {
[build.sc-64] [error]                                                   ^
[build.sc-64] [error] one error found
[68/68] ============================== snakeIn5Minutes.runGame ==============================
1 tasks failed
```

**Comment by davesmith00000** [comment]
Hi @linux-root,

Refresh/pull the `main` branch again. I had a PR ready that upgrades this demo to more modern lib versions.

Also I've just discovered that Indigo isn't compatible with Mill 0.12.x 😞 

However, that isn't a problem for you, just _change your command_ as follows (after updating the branch):

```diff
-mill snakeIn5Minutes.runGame
+./mill snakeIn5Minutes.runGame
```

..and it'll work.

**Comment by linux-root** [comment]
> Hi @linux-root,
> 
> Refresh/pull the `main` branch again. I had a PR ready that upgrades this demo to more modern lib versions.
> 
> Also I've just discovered that Indigo isn't compatible with Mill 0.12.x 😞
> 
> However, that isn't a problem for you, just _change your command_ as follows (after updating the branch):
> 
> ```diff
> -mill snakeIn5Minutes.runGame
> +./mill snakeIn5Minutes.runGame
> ```
> 
> ..and it'll work.

Hi @davesmith00000, it works like a charm. I really need this simple example to learn Indigo. Thank you for helping!
